### ISSUE TITLE
Empty Cdata

### ISSUE THREAD

**Issue by willm** [justinwilaby/sax-wasm#85]
**Describe the bug**
Bug when cdata follows empty cdata

**To Reproduce**

Add the following test to the `cdata.spec.ts` file

```javascript
  it("should support empty cdata", () => {
    parser.write(
      Buffer.from(`<div>
        <div>
          <![CDATA[]]>
        </div>
        <div>
          <![CDATA[something]]>
        </div>
      </div>`),
    );
    const { value } = _data[0];
    strictEqual(value, "something");
  });


```

**Expected behavior**
See the assertion

**Desktop (please complete the following information):**
 - OS:  Linux
 - Browser node 18
 - Version 2.2.1

**Additional context**

**Comment by willm** [comment]
Thank you very much for looking into this issue, however, when I upgrade to 2.3, it seems there are issues with the way the package is built.

`import {SAXParser} from "sax-wasm";`

raises an error at runtime

```
node:internal/modules/esm/resolve:275
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/test/node_modules/sax-wasm/lib/esm/saxWasm' imported from /tmp/test/node_modules/sax-wasm/lib/esm/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///tmp/test/node_modules/sax-wasm/lib/esm/saxWasm'
}

Node.js v22.12.0
```

One difference I noticed is that the contents of the lib directory is different, for example, there is a new `node_modules/sax-wasm/lib/esm` directory. I wonder if this was compiled with different settings to version 2.2.4?

Also I noticed the stream options got removed, is this related to the fix or just and additional change?

**Comment by justinwilaby** [comment]
Yep. Looks like there may be a problem with the "exports" in the package.json. Interestingly, adding a `.js` to the export resolves it.

`export * from './saxWasm.js';`

I'll get this sorted out and release a patch. Thanks for catching this!

**Comment by willm** [comment]
Hi thanks again for this, this has fixed the issue locally for me, however I'm getting the same error when deployed to aws lambda. I'm not able to reproduce it locally yet but will report back if I find anything.

**Comment by justinwilaby** [comment]
@willm - Try v2.3.2 which has some fixes for the exports when using node 18 or 20. If it's still not working, I'll get you back on track today.

**Comment by willm** [comment]
My tests seem to work with this new version at first glance, will do more testing in the coming days - thank you for being so active in feedback!

**Comment by justinwilaby** [comment]
You're welcome!
